old_sound_rabbit_mq:
  connections:
    default:
      url: '%env(RABBITMQ_URL)%'
  producers:
    add_teachers_skills:
      connection: default
      exchange_options: {name: 'old_sound_rabbit_mq.add_teachers_skills', type: direct}
    send_notification:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.send_notification', type: topic }

  consumers:
    add_teachers_skills:
      connection: default
      exchange_options: {name: 'old_sound_rabbit_mq.add_teachers_skills', type: direct}
      queue_options: {name: 'old_sound_rabbit_mq.consumer.add_teachers_skills'}
      callback: App\Consumer\AddTeachersSkills\Consumer
      idle_timeout: 300
      idle_timeout_exit_code: 0
      graceful_max_execution:
        timeout: 1800
        exit_code: 0
      qos_options: {prefetch_size: 0, prefetch_count: 1, global: false}
    send_notification.email:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.send_notification', type: topic }
      queue_options:
        name: 'old_sound_rabbit_mq.consumer.send_notification.email'
        routing_keys: [ !php/const App\Entity\User::EMAIL_NOTIFICATION ]
      callback: App\Consumer\SendEmailNotification\Consumer
      idle_timeout: 300
      idle_timeout_exit_code: 0
      graceful_max_execution:
        timeout: 1800
        exit_code: 0
      qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
    send_notification.sms:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.send_notification', type: topic }
      queue_options:
        name: 'old_sound_rabbit_mq.consumer.send_notification.sms'
        routing_keys: [ !php/const App\Entity\User::SMS_NOTIFICATION ]
      callback: App\Consumer\SendSmsNotification\Consumer
      idle_timeout: 300
      idle_timeout_exit_code: 0
      graceful_max_execution:
        timeout: 1800
        exit_code: 0
      qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }