old_sound_rabbit_mq:
  connections:
    default:
      url: '%env(RABBITMQ_URL)%'
  producers:
    add_teachers_skills:
      connection: default
      exchange_options: {name: 'old_sound_rabbit_mq.add_teachers_skills', type: direct}
    send_notification:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.send_notification', type: topic }
    update_skill:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.update_skill', type: x-consistent-hash }

  consumers:
    add_teachers_skills:
      connection: default
      exchange_options: {name: 'old_sound_rabbit_mq.add_teachers_skills', type: direct}
      queue_options: {name: 'old_sound_rabbit_mq.consumer.add_teachers_skills'}
      callback: App\Consumer\AddTeachersSkills\Consumer
      idle_timeout: 300
      idle_timeout_exit_code: 0
      graceful_max_execution:
        timeout: 1800
        exit_code: 0
      qos_options: {prefetch_size: 0, prefetch_count: 1, global: false}
    send_notification.email:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.send_notification', type: topic }
      queue_options:
        name: 'old_sound_rabbit_mq.consumer.send_notification.email'
        routing_keys: [ !php/const App\Entity\User::EMAIL_NOTIFICATION ]
      callback: App\Consumer\SendEmailNotification\Consumer
      idle_timeout: 300
      idle_timeout_exit_code: 0
      graceful_max_execution:
        timeout: 1800
        exit_code: 0
      qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
    send_notification.sms:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.send_notification', type: topic }
      queue_options:
        name: 'old_sound_rabbit_mq.consumer.send_notification.sms'
        routing_keys: [ !php/const App\Entity\User::SMS_NOTIFICATION ]
      callback: App\Consumer\SendSmsNotification\Consumer
      idle_timeout: 300
      idle_timeout_exit_code: 0
      graceful_max_execution:
        timeout: 1800
        exit_code: 0
      qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
    update_skill_0:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.update_skill', type: x-consistent-hash }
      queue_options: { name: 'old_sound_rabbit_mq.consumer.update_skill_0', routing_key: '100' }
      callback: App\Consumer\UpdateSkill\Consumer0
      idle_timeout: 300
      idle_timeout_exit_code: 0
      graceful_max_execution:
        timeout: 20
        exit_code: 0
      qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
    update_skill_1:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.update_skill', type: x-consistent-hash }
      queue_options: { name: 'old_sound_rabbit_mq.consumer.update_skill_1', routing_key: '100' }
      callback: App\Consumer\UpdateSkill\Consumer1
      idle_timeout: 300
      idle_timeout_exit_code: 0
      graceful_max_execution:
        timeout: 1800
        exit_code: 0
      qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
    update_skill_2:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.update_skill', type: x-consistent-hash }
      queue_options: { name: 'old_sound_rabbit_mq.consumer.update_skill_2', routing_key: '100' }
      callback: App\Consumer\UpdateSkill\Consumer2
      idle_timeout: 300
      idle_timeout_exit_code: 0
      graceful_max_execution:
        timeout: 1800
        exit_code: 0
      qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
    update_skill_3:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.update_skill', type: x-consistent-hash }
      queue_options: { name: 'old_sound_rabbit_mq.consumer.update_skill_3', routing_key: '100' }
      callback: App\Consumer\UpdateSkill\Consumer3
      idle_timeout: 300
      idle_timeout_exit_code: 0
      graceful_max_execution:
        timeout: 1800
        exit_code: 0
      qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
    update_skill_4:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.update_skill', type: x-consistent-hash }
      queue_options: { name: 'old_sound_rabbit_mq.consumer.update_skill_4', routing_key: '100' }
      callback: App\Consumer\UpdateSkill\Consumer4
      idle_timeout: 300
      idle_timeout_exit_code: 0
      graceful_max_execution:
        timeout: 1800
        exit_code: 0
      qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
    update_skill_5:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.update_skill', type: x-consistent-hash }
      queue_options: { name: 'old_sound_rabbit_mq.consumer.update_skill_5', routing_key: '100' }
      callback: App\Consumer\UpdateSkill\Consumer5
      idle_timeout: 300
      idle_timeout_exit_code: 0
      graceful_max_execution:
        timeout: 1800
        exit_code: 0
      qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
    update_skill_6:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.update_skill', type: x-consistent-hash }
      queue_options: { name: 'old_sound_rabbit_mq.consumer.update_skill_6', routing_key: '100' }
      callback: App\Consumer\UpdateSkill\Consumer6
      idle_timeout: 300
      idle_timeout_exit_code: 0
      graceful_max_execution:
        timeout: 1800
        exit_code: 0
      qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
    update_skill_7:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.update_skill', type: x-consistent-hash }
      queue_options: { name: 'old_sound_rabbit_mq.consumer.update_skill_7', routing_key: '100' }
      callback: App\Consumer\UpdateSkill\Consumer7
      idle_timeout: 300
      idle_timeout_exit_code: 0
      graceful_max_execution:
        timeout: 1800
        exit_code: 0
      qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
    update_skill_8:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.update_skill', type: x-consistent-hash }
      queue_options: { name: 'old_sound_rabbit_mq.consumer.update_skill_8', routing_key: '100' }
      callback: App\Consumer\UpdateSkill\Consumer8
      idle_timeout: 300
      idle_timeout_exit_code: 0
      graceful_max_execution:
        timeout: 1800
        exit_code: 0
      qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
    update_skill_9:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.update_skill', type: x-consistent-hash }
      queue_options: { name: 'old_sound_rabbit_mq.consumer.update_skill_9', routing_key: '100' }
      callback: App\Consumer\UpdateSkill\Consumer9
      idle_timeout: 300
      idle_timeout_exit_code: 0
      graceful_max_execution:
        timeout: 1800
        exit_code: 0
      qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }