# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Doctrine\MigrationEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    App\Service\GreeterService:
        arguments:
            $greet: 'Hello'

    App\Service\AuthService:
        arguments:
            $tokenTTL: '%env(JWT_TTL_SEC)%'

    App\Client\StatsdAPIClient:
        arguments:
            - graphite
            - 8125
            - my_app

    App\Service\AsyncService:
        calls:
            - [ 'registerProducer', [ !php/const App\Service\AsyncService::ADD_TEACHERS_SKILLS, '@old_sound_rabbit_mq.add_teachers_skills_producer' ] ]
            - [ 'registerProducer', [ !php/const App\Service\AsyncService::SEND_NOTIFICATION,    '@old_sound_rabbit_mq.send_notification_producer'] ]
            - [ 'registerProducer', [ !php/const App\Service\AsyncService::UPDATE_SKILL,    '@old_sound_rabbit_mq.update_skill_producer'] ]
              
    App\Consumer\UpdateSkill\Consumer0:
        class: App\Consumer\UpdateSkill\Consumer
        arguments:
            $key: 'update_skill_0'

    App\Consumer\UpdateSkill\Consumer1:
        class: App\Consumer\UpdateSkill\Consumer
        arguments:
            $key: 'update_skill_1'

    App\Consumer\UpdateSkill\Consumer2:
        class: App\Consumer\UpdateSkill\Consumer
        arguments:
            $key: 'update_skill_2'

    App\Consumer\UpdateSkill\Consumer3:
        class: App\Consumer\UpdateSkill\Consumer
        arguments:
            $key: 'update_skill_3'

    App\Consumer\UpdateSkill\Consumer4:
        class: App\Consumer\UpdateSkill\Consumer
        arguments:
            $key: 'update_skill_4'

    App\Consumer\UpdateSkill\Consumer5:
        class: App\Consumer\UpdateSkill\Consumer
        arguments:
            $key: 'update_skill_5'

    App\Consumer\UpdateSkill\Consumer6:
        class: App\Consumer\UpdateSkill\Consumer
        arguments:
            $key: 'update_skill_6'

    App\Consumer\UpdateSkill\Consumer7:
        class: App\Consumer\UpdateSkill\Consumer
        arguments:
            $key: 'update_skill_7'

    App\Consumer\UpdateSkill\Consumer8:
        class: App\Consumer\UpdateSkill\Consumer
        arguments:
            $key: 'update_skill_8'

    App\Consumer\UpdateSkill\Consumer9:
        class: App\Consumer\UpdateSkill\Consumer
        arguments:
            $key: 'update_skill_9'            